export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";

export const GET_PRODUCTS_ELECTRONICS = "GET_PRODUCTS_ELECTRONICS";
export const GET_PRODUCTS_JEWELRY = "GET_PRODUCTS_JEWELRY";
export const GET_PRODUCTS_MEN = "GET_PRODUCTS_MEN";
export const GET_PRODUCTS_WOMEN = "GET_PRODUCTS_WOMEN";
